### ISSUE TITLE
BACKEND: Setup mail server

### ISSUE THREAD

**Issue by dbridenbeck** [codeforpdx/dwellingly-app#335] opened 2020-09-14 22:34 UTC
**Purpose**
Setup our mail server to allow the backend to send emails (e.g. - look at the `email` resource's `send_reset_password_msg` method: https://github.com/codeforpdx/dwellinglybackend/blob/development/resources/email.py)

**Proposed Solution**
I'm not quite sure what the right method is to configure this, but it looks like the code in question is lines 42 - 54 in app.py:
```
#configure mail server
    app.config['MAIL_SERVER'] = 'smtp.gmail.com'
    app.config['MAIL_PORT'] = 465
    app.config['MAIL_USE_TLS'] = False
    app.config['MAIL_USE_SSL'] = True
    app.config['MAIL_DEBUG'] = True #same as app
    app.config['MAIL_USERNAME'] = "dwellingly@gmail.com" #not active
    app.config['MAIL_PASSWORD'] = "1234567thisisnotreal"
    # app.config['MAIL_USERNAME'] = os.environ['EMAIL_USERNAME']
    # app.config['MAIL_PASSWORD'] = os.environ['EMAIL_PASSWORD']
    # app.config['MAIL_DEFAULT_SENDER'] = 'noreply@dwellingly.com'
    app.config['MAIL_MAX_EMAILS'] = 3
    app.config['MAIL_ASCII_ATTACHMENTS'] = False
```

**Acceptance Criteria**
Please list the requirements the implementation of this feature should meet.
- [ ] Hitting /api/forgot-password with the payload of `{"email": "user2@dwellingly.org"}` should successfully send an email to that email address (or any other email address as long as the email is associated with a dwellingly user).

**Mockup Screenshot or Page Number**
N/A

**Comment by NickSchimek** [comment] 2020-09-15 00:19
Hi @darenschaad Thanks for creating an issue. Unfortunately this is currently the expected behavior. As you can see on this line `app.config['MAIL_PASSWORD'] = "1234567thisisnotreal"` the password is not real and the email address is not yet active. 

Ideally when doing development and testing the mail library would be suppressed, so that when the endpoint is hit in development or the testing environment the application will act like it sent out an email. Unfortunately the backend is currently not setup to distinguish between different environments. Hence, the mail server is not automatically suppressed.

For frontend testing purposes there are at least two choices that I can think of. 

If you actually want to send out a live email then set the username and password to an account you own (you may have to lower your security settings on your gmail account, or whatever account you use.)

If you just want to hit the endpoint without an error then you can suppress the mail server by adding this line to app.config
`app.config['MAIL_SUPPRESS_SEND'] = True` <- This would normally be automatically set to true in the dev and test environments.

There is currently an open ticket to address refactoring the configs into different environments for the backend. Closing this issue as it is more or less a duplicate of codeforpdx/dwellingly-app/issues/307

**Closed as completed by NickSchimek** 2020-09-15 00:19 UTC
